### PR TITLE
Part 2/3 - Optimize OkioMessageDigest performance 

### PR DESCRIPTION
**Pull request by kevincianfarini**
This is a WIP PR for optimizing `OkioMessageDigest` with accompanying JMH benchmarks.

### CODE REVIEW

**Comment by kevincianfarini** [comment]
@swankjesse Thoughts on how to benchmark `OkioMessageDigest` since the `jmh` package can't see okio internal code? 

I guess we could combine parts 2 and 3 for exposing a public API to hashing in this PR, but I don't know if that's how you'd like to proceed.

**Comment by swankjesse** [comment]
@kevincianfarini make the parts you need public for now, and we’ll clear it up before release.

**Comment by kevincianfarini** [comment]
Alright I've finally had some time to sit down and work through the benchmarks. It seems that `OkioMessageDigest` is currently about an order of magnitude slower than Java 14's `MessageDigest`. 

```
Benchmark                       (algorithm)  (messageSize)  Mode  Cnt     Score     Error  Units
JvmMessageDigestBenchmark.hash        SHA-1            100  avgt    5     0.498 ±   0.008  us/op
JvmMessageDigestBenchmark.hash        SHA-1        1048576  avgt    5  3622.972 ±  15.425  us/op
JvmMessageDigestBenchmark.hash      SHA-256            100  avgt    5     0.431 ±   0.007  us/op
JvmMessageDigestBenchmark.hash      SHA-256        1048576  avgt    5  2512.378 ±  12.493  us/op
JvmMessageDigestBenchmark.hash      SHA-512            100  avgt    5     0.304 ±   0.006  us/op
JvmMessageDigestBenchmark.hash      SHA-512        1048576  avgt    5  1765.034 ± 154.337  us/op
JvmMessageDigestBenchmark.hash          MD5            100  avgt    5     0.356 ±   0.018  us/op
JvmMessageDigestBenchmark.hash          MD5        1048576  avgt    5  2498.630 ± 144.882  us/op
```
```
 Benchmark                        (algorithm)  (messageSize)  Mode  Cnt      Score     Error  Units
 OkioMessageDigestBenchmark.hash        SHA-1            100  avgt    5      7.309 ±   0.129  us/op
 OkioMessageDigestBenchmark.hash        SHA-1        1048576  avgt    5  35893.400 ± 342.705  us/op
 OkioMessageDigestBenchmark.hash      SHA-256            100  avgt    5      4.156 ±   0.052  us/op
 OkioMessageDigestBenchmark.hash      SHA-256        1048576  avgt    5  20524.018 ± 209.808  us/op
 OkioMessageDigestBenchmark.hash      SHA-512            100  avgt    5      4.643 ±   0.034  us/op
 OkioMessageDigestBenchmark.hash      SHA-512        1048576  avgt    5  19095.547 ± 176.704  us/op
 OkioMessageDigestBenchmark.hash          MD5            100  avgt    5      5.491 ±   0.117  us/op
 OkioMessageDigestBenchmark.hash          MD5        1048576  avgt    5  27096.753 ± 407.171  us/op
```

Let's see what we can do about this. I'm going to start with manual loop unrolling and see how far that gets us.

**Comment by swankjesse** [comment]
Try to see what happens if you remove 100% of allocations.

**Comment by kevincianfarini** [comment]
@swankjesse any suggestions on profilers? I've briefly read about JMC but it appears to be missing from OpenJDK. I'm thinking it's probably a good idea to be guided by a profiler than blindly optimize. 

Thank is a first for me so any help is appreciated :)

**Comment by swankjesse** [comment]
Here’s some optimizations of your code that get very close to the JDK’s performance.
https://github.com/square/okio/compare/master...jwilson.0829.faster?expand=1#files_bucket

**Comment by swankjesse** [comment]
(Above optimizes SHA-1 only!)

**Comment by kevincianfarini** [comment]
Thanks. That's a great reference. I'll hopefully get around to this soon.

**Comment by kevincianfarini** [comment]
Progress :) hoping to get this done this week. We'll see...

```
Benchmark                    (algorithm)  (messageSize)  Mode  Cnt      Score      Error  Units
MessageDigestBenchmark.jvm         SHA-1            100  avgt    5      0.511 ±    0.013  us/op
MessageDigestBenchmark.jvm         SHA-1        1048576  avgt    5   3701.149 ±   75.609  us/op
MessageDigestBenchmark.okio        SHA-1            100  avgt    5      1.704 ±    0.041  us/op
MessageDigestBenchmark.okio        SHA-1        1048576  avgt    5  14612.782 ± 2235.386  us/op
```

**Comment by swankjesse** [comment]
@kevincianfarini please take the SHA-1 optimizations I posted and benchmark them?

**Comment by kevincianfarini** [comment]
Yup sure thing. I will pull in your changes. Sorry!

**Comment by kevincianfarini** [comment]
These are the numbers we're working with right now on my machine. MD5 hasn't been updated yet. 

```
Benchmark                    (algorithm)  (messageSize)  Mode  Cnt      Score     Error  Units
MessageDigestBenchmark.jvm         SHA-1            100  avgt    5      0.501 ±   0.004  us/op
MessageDigestBenchmark.jvm         SHA-1        1048576  avgt    5   3590.565 ±  32.123  us/op
MessageDigestBenchmark.jvm       SHA-256            100  avgt    5      0.429 ±   0.011  us/op
MessageDigestBenchmark.jvm       SHA-256        1048576  avgt    5   2916.054 ± 434.554  us/op
MessageDigestBenchmark.jvm       SHA-512            100  avgt    5      0.299 ±   0.009  us/op
MessageDigestBenchmark.jvm       SHA-512        1048576  avgt    5   1769.964 ± 253.518  us/op
MessageDigestBenchmark.jvm           MD5            100  avgt    5      0.347 ±   0.009  us/op
MessageDigestBenchmark.jvm           MD5        1048576  avgt    5   2450.680 ±  29.236  us/op
MessageDigestBenchmark.okio        SHA-1            100  avgt    5      0.743 ±   0.015  us/op
MessageDigestBenchmark.okio        SHA-1        1048576  avgt    5   3817.994 ±  48.900  us/op
MessageDigestBenchmark.okio      SHA-256            100  avgt    5      1.014 ±   0.012  us/op
MessageDigestBenchmark.okio      SHA-256        1048576  avgt    5   5281.753 ±  88.101  us/op
MessageDigestBenchmark.okio      SHA-512            100  avgt    5      1.319 ±   0.012  us/op
MessageDigestBenchmark.okio      SHA-512        1048576  avgt    5   5049.412 ±  98.693  us/op
MessageDigestBenchmark.okio          MD5            100  avgt    5      5.785 ±   0.092  us/op
MessageDigestBenchmark.okio          MD5        1048576  avgt    5  31344.226 ± 511.381  us/op
```

The JDK implementation are still ~2-5x faster for SHA-256 and SHA-512. My next thought is to do some manual loop unrolling. Is it possible to check if the kotlin compiler is unrolling loops for us already?

**Comment by kevincianfarini** [comment]
Some minor improvements from avoiding for loops with iterators, like `for (i in 0 until 10)`

```
Benchmark                    (algorithm)  (messageSize)  Mode  Cnt      Score     Error  Units
MessageDigestBenchmark.jvm         SHA-1            100  avgt    5      0.496 ±   0.005  us/op
MessageDigestBenchmark.jvm         SHA-1        1048576  avgt    5   3590.737 ± 124.235  us/op
MessageDigestBenchmark.jvm       SHA-256            100  avgt    5      0.424 ±   0.004  us/op
MessageDigestBenchmark.jvm       SHA-256        1048576  avgt    5   2883.688 ± 507.255  us/op
MessageDigestBenchmark.jvm       SHA-512            100  avgt    5      0.298 ±   0.012  us/op
MessageDigestBenchmark.jvm       SHA-512        1048576  avgt    5   1752.465 ± 197.249  us/op
MessageDigestBenchmark.jvm           MD5            100  avgt    5      0.341 ±   0.002  us/op
MessageDigestBenchmark.jvm           MD5        1048576  avgt    5   2444.207 ±  49.706  us/op
MessageDigestBenchmark.okio        SHA-1            100  avgt    5      0.741 ±   0.008  us/op
MessageDigestBenchmark.okio        SHA-1        1048576  avgt    5   3718.821 ±  24.774  us/op
MessageDigestBenchmark.okio      SHA-256            100  avgt    5      0.973 ±   0.011  us/op
MessageDigestBenchmark.okio      SHA-256        1048576  avgt    5   5481.669 ±  62.714  us/op
MessageDigestBenchmark.okio      SHA-512            100  avgt    5      1.223 ±   0.026  us/op
MessageDigestBenchmark.okio      SHA-512        1048576  avgt    5   5163.253 ±  99.770  us/op
MessageDigestBenchmark.okio          MD5            100  avgt    5      5.738 ±   0.033  us/op
MessageDigestBenchmark.okio          MD5        1048576  avgt    5  31546.956 ± 555.596  us/op
```

**Comment by swankjesse** [comment]
Use 'show Kotlin bytecode' in IntelliJ, followed by 'decompile to Java' to see what the compiler is doing. Once there's no allocations try to inline trivial methods?

**Comment by swankjesse** [comment]
(using the `inline` keyword!)

**Comment by kevincianfarini** [comment]
Love it! Should have thought of that myself ha. Thanks

**Comment by kevincianfarini** [comment]
Unrolling certainly isn't happening. Hopefully tomorrow I can try it out on one of the classes to see if it helps.

**Comment by JakeWharton** [comment]
`for (i in 0 until 10)` will not use an iterator

**Comment by kevincianfarini** [comment]
Looking at the source code for [SHA3 in OpenJDK ](https://github.com/openjdk/jdk/blob/fd28aad72d3a13fbc2eb13293d40564e471414f3/src/java.base/share/classes/sun/security/provider/SHA3.java) I'm starting to wonder if the algorithms chosen for our SHA-256/512 implementations are inefficient. I've noticed many references to [this](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.202.pdf) document that I'm going to give a read and see what I can run with. 

I wouldn't be surprised considering the initial implementation was adapted from psuedocode on Wikipedia. 

Seeing as MD5 and SHA1 are the only algorithms with branchy code in the inner loop I think that manual unrolling may actually help. I'm going to start there and see what that affords us. The OpenJDK source code isn't too different from our own. The amount of difference between our SHA3 implementations and theirs makes me wonder, though.

**Comment by kevincianfarini** [comment]
> `for (i in 0 until 10)` will not use an iterator

@JakeWharton you're absolutely correct. After deompiling the generated bytecode I see now that no iterator is used. My initial intuition was based on `IntProgression` inheriting from `Iterable`. Glad the compiler is smart enough to get rid of that!

**Comment by JakeWharton** [comment]
Please do not look at OpenJDK source since it is GPL. You cannot use anything from it and have your contributions accepted. Even learning from it is likely considered creating a derivative work. Please use reference material that we can cite with permission or which has a compatible license.

**Comment by kevincianfarini** [comment]
@JakeWharton yup learned that the hard way. Jesse and I have already spoken. I guess this is a good less for me to learn now rather than later. Thanks for the guidance!

**Pull request closed without merging**
