### PR TITLE
Add isEmpty() convenience method.

### PR DESCRIPTION
**Pull request by JakeWharton**
`size() == 0` is so 2014

### CODE REVIEW

**Comment by swankjesse** [comment]
I know I suggested this. Do we want both this and `exhausted()` ?

**Comment by swankjesse** [comment]
LGTM

**Comment by JakeWharton** [comment]
No. I think we just keep forgetting to use it!

**Comment by JakeWharton** [comment]
Although perhaps the semantics of `exhausted()` when dealing with a buffer justify this method because `exhausted()` sounds like something you check while reading whereas `isEmpty()` is a check that can be made after conditionally writing.

**Comment by JakeWharton** [comment]
Examples where `isEmpty` would probably read better:
```java
if (content.exhausted()) {
  throw new IllegalStateException("Form encoded body must have at least one part.");
}
```
```java
while (readBuffer.exhausted() && !finished && !closed && errorCode == null) {
  waitForIo(); // <-- maybe writes into readBuffer
}
```
This one isn't so bad, but would read even better:
```java
boolean wasEmpty = readBuffer.exhausted();
```

**Pull request closed without merging**
