### PR TITLE
Prevent calling scheduleTimeout twice on an AsyncTimeout

### PR DESCRIPTION
**Pull request by findepi**
Invoking `enter` concurrently on an `AsyncTimeout` instance may lead to
`scheduleTimeout` being invoked twice.  If `scheduleTimeout` is called
on an `AsyncTimeout` instance that is already scheduled, it could lead
to a cycle in the single linked list starting with `head`, which in turn
would lead to an infinite loop in `cancelScheduledTimeout`.

Fixes: https://github.com/square/okio/issues/624

cc @wendigo @losipiuk

### CODE REVIEW

**Comment by swankjesse** [comment]
How does this happen? Doesn’t `enter()` / `exit()` defend against this?

**Comment by findepi** [comment]
> How does this happen?

`enter` is not synchronized


However, I am not saying this is the _only_ explanation for the infinite loop in `cancelScheduledTimeout` due to a cycle.
This is _a_ potential explanation only.

**Comment by swankjesse** [comment]
Lets move all access to `inQueue` into the synchronized `scheduleTimeout` function and `cancelScheduledTimeout` functions? That way we can avoid the O(N) loop!

**Comment by findepi** [comment]
We have O(n) for insertion anyway.
Also, `scheduleTimeout` is static, so i can't check `inQueue` there. Do you mean to pass the object as instance (this) rather than as parameter? (i don't speak Kotlin, so i am calling these things wrong, sorry)

we could also make `enter` and `exit` synchronized as well, but I am not versed in the okio to appreciate the consequences

**Comment by swankjesse** [comment]
I think for `scheduleTimeout` and `cancelScheduledTimeout` we’d just dereference `AsyncTimeout.inQueue`, which is the passed-in argument.

**Comment by findepi** [comment]
@swankjesse i reworked based on your suggestion.
I also added a test which reproduced the problem pretty consistently on my machine.
The test does 10000 iterations, while on my machine the deadlock occurs between 100 and 200 iteration.
With the code fixed, it is not the longest test in `AsyncTimeoutTest`, e.g. taking half the time of `instancesAddedAtFront`.

i struggled with formatting the code in the appropriate way, and some guidance would be helpful.

**Comment by swankjesse** [comment]
The test ignores an IllegalStateException... when you observed the infinite loop in the wild was it after ignoring such exceptions?

**Comment by findepi** [comment]
i observed this in Presto's project testing infrastructure (https://github.com/prestosql/presto/issues/5422).
There we use https://github.com/testcontainers/testcontainers-java/, which uses https://github.com/docker-java/docker-java, which uses `okhttp`.

AFAICT there was no `IllegalStateException` propagated to our code.

**Comment by findepi** [comment]
Is there anything i can improve in my PR?

**Comment by findepi** [comment]
rebased

**Comment by swankjesse** [comment]
Got it. I suspect there's some concurrency problems in there. This PR is a good idea so things fall more gracefully in the event of concurrency problems.

**Comment by swankjesse** [comment]
Thanks! I merged this manually after reverting some of the naming changes. I also dropped the concurrency test.

**Pull request closed without merging**
