### PR TITLE
Remove JDK dependencies from Options

### PR DESCRIPTION
**Pull request by Egorand**

### CODE REVIEW

**Comment by JakeWharton** [comment]
The error doesn't really indicate the change. Any idea what it is?

**Comment by Egorand** [comment]
I'm pretty sure it's because `kotlin.AbstractList` is not a typealias but actually a different class. The error points to `SegmentedByteString` which is `internal` and should be added to excludes.

**Comment by Egorand** [comment]
Like introducing our own `okio.AbstractList` and typealiasing it to `java.util.AbstractList`? Sure, but is it worth it? I think it's a perfectly fine breaking change for 2.0

**Comment by swankjesse** [comment]
Will somebody in 1.x be able to downcast Options to List? If that works I'm happy.

**Comment by Egorand** [comment]
I can actually do `java.util.List<ByteString> options = Options.of()` inside a Java file, although I don't completely understand how this works, as there are no typealiases in the hierarchy.. @JakeWharton is this a compiler trick? Would someone who has a pure-Java project with okio 2 and all necessary Kotlin dependencies on the classpath be able to compile this code?

**Comment by Egorand** [comment]
I just tried putting an okio JAR along with a Kotlin stdlib JAR into a Java-only project and casting `Options` to `java.util.List`, and it won't compile, hence you'll need kotlinc to be able to build the project. I'll decline the PR for now, but we might add our own `AbstractList` typealias going forward.

**Pull request closed without merging**
