### PR TITLE
Add 'Automatic-Module-Name' entry to manifest

### PR DESCRIPTION
**Pull request by kashike**
adds #339

### CODE REVIEW

**Comment by swankjesse** [comment]
I think we want `com.squareup.okio` ?

**Comment by JakeWharton** [comment]
That advice is for those whose package names are already prefixed with
something like com.squareup which this library is not.

**Comment by kashike** [comment]
@JakeWharton https://github.com/square/okhttp/pull/3743#issuecomment-361104656
Package name is `okio`: https://github.com/square/okio/tree/master/okio/src/main/java/okio.
> Your module name should be the same as the package name in that jar file, unless you have a good reason otherwise. ie. you as a human are deciding that one package is the base, and assigning that as the module name. Thus the okhttp3 pom.xml would declare a module name of okhttp3 (I dislike that this is not com.squareup.okhttp3 but you should still match the package name)

**Comment by JakeWharton** [comment]
I don't agree with that, and it's not official policy anyway.

**Comment by kashike** [comment]
Alright, there you go then.

**Pull request merged**
