### PR TITLE
Fix GzipSource to handle large files on AOSP.

### PR DESCRIPTION
**Pull request by swankjesse**
Closes: https://github.com/square/okio/issues/250

### CODE REVIEW

**Comment by swankjesse** [comment]
The tests were already passing on the JVM. But I ran ’em against libcore and they failed there. This gets ’em working everywhere.

**Comment by JakeWharton** [comment]
Lgtm.

**Comment by JakeWharton** [comment]
What about `GzipSink`?

**Comment by swankjesse** [comment]
It was never broken!

**Comment by swankjesse** [comment]
... though I was thinking about this, and it’s worth changing for symmetry.
https://github.com/square/okio/pull/253

**Comment by JakeWharton** [comment]
Agreed

**Pull request merged**
