### PR TITLE
Just use 'okio' for the automatic module name.

### PR DESCRIPTION
**Pull request by swankjesse**

### CODE REVIEW

**Comment by JakeWharton** [comment]
What changed your mind? I prefer the old one.

**Comment by kashike** [comment]
https://github.com/square/okhttp/pull/3743#issuecomment-362888517

**Comment by JakeWharton** [comment]
I don't want to use 'retrofit2' for Retrofit. Matching package names is for people who have qualified package names.

**Comment by swankjesse** [comment]
Discussed offline. Automatic-Module-Names shall be package names!

**Pull request merged**
