### PR TITLE
Switch to a hierarchical project structure

### PR DESCRIPTION
**Pull request by swankjesse**
https://kotlinlang.org/docs/migrating-multiplatform-project-to-14.html#migrate-to-the-hierarchical-project-structure

### CODE REVIEW

**Comment by JakeWharton** [comment]
Dupe of #980?

**Comment by swankjesse** [comment]
I think that one's more ambitious. Here I don't want to change the Kotlin version, I'm just trying to produce an artifact that works with a consuming project that's itself hierarchical.

**Comment by swankjesse** [comment]
This is too rough and triggering compiler bugs. For example, a default parameter in an `expect` file isn’t honored.

```
e: /Users/runner/work/okio/okio/okio/src/nativeMain/kotlin/okio/PosixFileSystem.kt: (32, 49): No value passed for parameter 'normalize'
> Task :okio:compileNativeMainKotlinMetadata FAILED
e: /Users/runner/work/okio/okio/okio/src/nativeMain/kotlin/okio/PosixFileSystem.kt: (33, 52): No value passed for parameter 'normalize'
```

**Comment by swankjesse** [comment]
That one’s https://youtrack.jetbrains.com/issue/KT-48811

**Comment by swankjesse** [comment]
And the last is this one: https://youtrack.jetbrains.com/issue/KT-47430

**Pull request closed without merging**
