### PR TITLE
Make Flushable available in common and fully implement sink in common

### PR DESCRIPTION
**Pull request by FabianTerhorst**
After trying to extend ``Sink`` in a common project i noticed it isn't possible because it is a `expect interface`. 
In this PR i make ``Sink`` a ``interface`` by making ``Flushable`` available in the common project. Same as it was done with ``Closeable``.

### CODE REVIEW

**Review by Egorand — APPROVED** [review]
Nice, I like it!

**Comment by JakeWharton** [comment]
Can you explain the problem more? Nothing should prevent you from implementing the `Sink` interface in common as it is today.

**Comment by FabianTerhorst** [comment]
I fixed the problem that the inheritance didn't worked by adding:
```kotlin
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().all {
    kotlinOptions {
        jvmTarget = "1.8"
        freeCompilerArgs += "-Xjvm-default=all"
    }
}
```
Seems like that was unrelated to ``expect interface``.

**Comment by FabianTerhorst** [comment]
But i think the pull request is still valid since it reduces the code.

**Comment by JakeWharton** [comment]
It reduces code at the expense of exposing an otherwise unused public API. We begrudgingly expose `Closeable` to support the `use` extension in common code. There's no general purpose usage of `Flushable`.

As a library I much prefer to keep the public API surface as small as possible even if it increases the maintenance burden. Much better to burden us than our users.

**Comment by FabianTerhorst** [comment]
Ok, thats understandable. When https://youtrack.jetbrains.com/issue/KT-37316 is resolved it probably would be more acceptable to do this change, because there would be no exposed api.

**Comment by swankjesse** [comment]
I wonder if we can we use this instead?
```
@Suppress("ACTUAL_WITHOUT_EXPECT")
```

**Comment by swankjesse** [comment]
No action on this for now. May revisit.

**Pull request closed without merging**
