### PR TITLE
Add OSGi metadata to Okio

### PR DESCRIPTION
**Pull request by lburgazzoli**
I've added some minimal tests for OSGi correctness that do not run by default as they are confined in the osgi maven profile.

Here how it looks in Apache Karaf 

```
Square :: Okio (78)
-------------------
Bnd-LastModified = 1451401650477
Build-Jdk = 1.8.0_66
Built-By = lburgazz
Created-By = Apache Maven Bundle Plugin
Manifest-Version = 1.0
Tool = Bnd-3.0.0.201509101326

Bundle-Description = A modern I/O API for Java
Bundle-License = http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-ManifestVersion = 2
Bundle-Name = Square :: Okio
Bundle-SymbolicName = com.squareup.okio.okio
Bundle-Version = 1.7.0.SNAPSHOT

Require-Capability = 
	osgi.ee;filter:=(&(osgi.ee=JavaSE)(version=1.7))

Export-Package = 
	okio;version=1.7.0.SNAPSHOT
```

### CODE REVIEW

**Comment by swankjesse** [comment]
The amount of work required here seems excessive. Is there a simpler way?

**Comment by lburgazzoli** [comment]
Most changes are required for test cases that need to bring up an osgi container, if you do not want them, you need maven-bundle-plugin only

**Comment by swankjesse** [comment]
I think the `maven-bundle-plugin` is good enough for me. If the tests fail, I’m not going to know enough to fix them anyway.

**Comment by lburgazzoli** [comment]
I will rework the PR tomorrow morning, late night here :-)

**Comment by swankjesse** [comment]
Thanks!

**Comment by lburgazzoli** [comment]
@swankjesse OSGi tests removed

**Comment by swankjesse** [comment]
Merged manually! Thanks!

**Pull request closed without merging**
