### PR TITLE
Try expect interfaces for Closeable, Flushable

### PR DESCRIPTION
**Pull request by swankjesse**
This fails due to a crashing bug in the Kotlin/JS compiler.

https://youtrack.jetbrains.com/issue/KT-28927

### CODE REVIEW

**Comment by JakeWharton** [comment]
What's the motivation for this change? Is there Okio-specific common code that abstracts over a Closeable or Flushable?

In SQLDelight we did Closeable but now I regret it and wish we just offered a specialized `SqlStatement.use` which delegated to `Closeable` on the JVM and did the dance manually on JS/native.

**Comment by swankjesse** [comment]
I wanna move Source and Sink to common properly rather than using expect classes.

**Comment by JakeWharton** [comment]
Is there an advantage to doing so aside from our own maintenance burden?

**Comment by swankjesse** [comment]
Just our maintenance burden! Closing for now.

**Pull request closed without merging**
